name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Use a consistent tag across build & push. You can change to github.sha or run_id if you prefer.
      IMAGE_TAG: ${{ github.sha }}
      REGISTRY: ghcr.io
      OWNER: rescrv
      REPO: brief-measure

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image (migrate up)
      run: docker build brief-measure --target brief-measure-migrate-up --tag ${REGISTRY}/${OWNER}/${REPO}-migrate-up:${IMAGE_TAG}

    - name: Build the Docker image (serve)
      run: docker build brief-measure --target brief-measure-serve --tag ${REGISTRY}/${OWNER}/${REPO}-serve:${IMAGE_TAG}

    - name: Push the docker image (migrate up)
      run: docker push ${REGISTRY}/${OWNER}/${REPO}-migrate-up:${IMAGE_TAG}

    - name: Push the docker image (serve)
      run: docker push ${REGISTRY}/${OWNER}/${REPO}-serve:${IMAGE_TAG}
